name: Release Tag & Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    name: Create Release Tag from Branch
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: branch
        run: |
          echo "branch_ref=$(git log -1 --pretty=format:'%D' | grep -o 'origin/release/[^, ]*' | head -n1 | sed 's/origin\///')" >> $GITHUB_OUTPUT

      - name: Set tag version
        id: tag
        run: |
          branch="${{ steps.branch.outputs.branch_ref }}"
          if [[ "$branch" =~ release/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            tag="${BASH_REMATCH[1]}"
            tag="v$tag"
          else
            last_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
            IFS='.' read -r v1 v2 v3 <<< "${last_tag#v}"
            tag="v$((v1)).$((v2)).$((v3+1))"
          fi
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG

      - name: Wait for Tag push
        run: sleep 5
  build-and-deploy-with-tag:
    name: Build and Deploy to Cloud Run
    needs: create-release-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.TAG }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: aviation-integration

      - name: Build Docker image
        run: gcloud builds submit --tag gcr.io/aviation-integration/aviation-integration

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy aviation-integration \
            --image gcr.io/aviation-integration/aviation-integration \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --memory=2Gi
